package.name = "warframe_optimizer"
package.version = "0.3.0"
package.edition = "2021"
package.repository = "https://github.com/ReallyMadHermit/wf_optimizer"
package.license = "CC-BY-NC-SA 4.0"

dependencies.ratatui = "0.29.0"
dependencies.rayon = "1.11.0"
dependencies.thousands = "0.2.0"

# Enable a large amount of optimization in the dev profile for dependencies.
profile.dev.package."*".opt-level = 3

profile.release.opt-level = 3
profile.release.lto = "fat"
profile.release.codegen-units = 1
profile.release.panic = "abort"
profile.release.strip = true
profile.release.incremental = false
profile.release.debug = false
profile.release.overflow-checks = false
